# Generated by Django 4.2.7 on 2023-11-15 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
                ('time_create', models.DateTimeField(default=datetime.datetime(2023, 11, 15, 12, 56, 20, 804293))),
            ],
        ),
    ]
